### ISSUE TITLE
一种新的绕过方式思路

### ISSUE THREAD

**Issue by U1805** [windbullet/koishi-plugin-qqurl-bypass#1]
推测官方检测 url 时是先经过安全检测判断域名的：

利用 `/echo https://q.qq.com/qqbot/` 机器人能正常输出 url

![图片](https://github.com/windbullet/koishi-plugin-qqurl-bypass/assets/45514638/e9a9d4f9-1b3d-4894-9eba-cfb4dd91326b)

因此，我们可以把原来的 url 放在官方域名后面混淆检测[doge]，效果如下：

![图片](https://github.com/windbullet/koishi-plugin-qqurl-bypass/assets/45514638/f8ca76ef-e854-424f-b72c-330ad7c29495)

这样的优点是可以直接复制后面的真实url去访问，不用删除字符或修改字符，可能方便点

**Comment by windbullet** [comment]
这样会让整个链接都变蓝，复制起来也不是那么方便
而且如何让用户知道该访问哪个部分也是一个问题
句号绕过模式同样能实现直接复制访问
